ALTER TABLE quotations ADD COLUMN store_id BIGINT UNSIGNED NULL AFTER id;
ALTER TABLE quotation_items ADD COLUMN batch_id BIGINT UNSIGNED NULL AFTER id;
ALTER TABLE quotation_items ADD COLUMN discount DECIMAL(8, 2) NULL AFTER price;
